### PR TITLE
Update screenshots in readme

### PR DESCRIPTION
**Pull request by helms-charity**
Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues
https://github.com/adobe/helix-sidekick-extension/issues/383

Thanks for contributing!

### CODE REVIEW

**Review by rofe — CHANGES_REQUESTED** [review]
You changed the screenshots from `png` to `jpg`, but README.md is still pointing to the `png` versions.

**Comment by helms-charity** [comment]
> You changed the screenshots from `png` to `jpg`, but README.md is still pointing to the `png` versions.

Thank you -- and fixed.

**Review by rofe — CHANGES_REQUESTED** [review]
@helms-charity I think the link to the "extension box" screenshot needs to be updated as well. At least https://github.com/helms-charity/helix-sidekick-extension#testing-a-local-chrome-extension still shows the Helix one.

**Review by rofe — APPROVED** [review]

**Pull request merged**
