### PR TITLE
fix: various security fixes

### PR DESCRIPTION
**Pull request by kptdobe**
Based on Kodiak findings: https://dashboard.kodiak.corp.adobe.com/#/findings/github.com/adobe/helix-sidekick-extension

### CODE REVIEW

**Comment by kptdobe** [comment]
The report UI is pretty bad, not clear what are all the error - some messages lead to different sources... this should address most of them, we'll need to re-check the dashboard after merge.

**Comment by rofe** [comment]
@kptdobe merge `main` into your branch to fix the tests.

**Comment by kptdobe** [comment]
@rofe thanks, tests passed now!

**Comment by kptdobe** [comment]
@rofe thanks, tests passed now!

**Review by rofe — APPROVED** [review]

**Pull request merged**
